services:
  - type: web
    name: roperia-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
